[chip-names-0]
"0xE3" = "LaserMan"
"0xE4" = "LaserMn2"
"0xE5" = "LaserMn3"

[chip-descriptions-0]
"0xE3" = "A laser\npierces\n1 thru"
"0xE4" = "A laser\npierces\n1 thru"
"0xE5" = "A laser\npierces\n1 thru"
