[chip-names-0]
"0xE7" = "ElecMan2"
"0xE8" = "ElecMan3"
"0xEA" = "SlashMn2"
"0xEB" = "SlashMn3"
"0xED" = "EraseMn2"
"0xEE" = "EraseMn3"
"0xF3" = "SpoutMn2"
"0xF4" = "SpoutMn3"
"0xF6" = "TmhkMan2"
"0xF7" = "TmhkMan3"
"0xF9" = "TenguMn2"
"0xFA" = "TenguMn3"
"0xFC" = "GrndMan2"
"0xFD" = "GrndMan3"
"0xFF" = "DustMan2"

[chip-names-1]
"0x00" = "DustMan3"
"0x02" = "BlastMn2"
"0x03" = "BlastMn3"
"0x05" = "DiveMan2"
"0x06" = "DiveMan3"
"0x0B" = "JudgeMn2"
"0x0C" = "JudgeMn3"
"0x0E" = "ElmntMn2"
"0x0F" = "ElmntMn3"
