[chip-names-0]
"0xEF" = "NumbrMan"
"0xF0" = "NumbrMn2"
"0xF1" = "NumbrMn3"

[chip-descriptions-0]
"0xEF" = "Bomb 3\nahead!\nHits 9sq"
"0xF0" = "Bomb 3\nahead!\nHits 9sq"
"0xF1" = "Bomb 3\nahead!\nHits 9sq"
