[chip-names-0]
"0x18" = "RollAro1"
"0x19" = "RollAro2"
"0x1A" = "RollAro3"

[chip-descriptions-0]
"0x18" = "RollArrow\ndestroys\nchips"
"0x19" = "RollArrow\ndestroys\nchips"
"0x1A" = "RollArrow\ndestroys\nchips"
