[chip-names-1]
"0x07" = "SerchMan"
"0x08" = "SerchMn[EX]"
"0x09" = "SerchMn[SP]"

[chip-descriptions-1]
"0x07" = ["Aim", "and fire", "5 shots"]
"0x08" = ["Aim", "and fire", "5 shots"]
"0x09" = ["Aim", "and fire", "5 shots"]
