[chips."0x0E3"]
name = "LaserMan"
description = ["A laser", "pierces", "1 thru"]
codes = ["L", "*"]
attack_element = 0
rarity = 2
element = "null"
class = "mega"
mb = 60
power = 100
behavior = { effect_flags = 0x47, counter_settings = 0x8A, dark_soul_usage = 0x00, unknown_0e = 0x04, lock_on = 0x00, object_spawn = {} }
artwork = { image = "laserman_image", palette = "laserman_palette_base" }

[chips."0x0E3".variants]
gregar = { artwork = { icon = 0x08729D50 } }
falzar = { artwork = { icon = 0x0872BE14 } }

[chips."0x0E4"]
name = "LaserMn[EX]"
description = ["A laser", "pierces", "1 thru"]
codes = ["L"]
attack_element = 0
rarity = 3
element = "null"
class = "mega"
mb = 80
power = 150
behavior = { effect_flags = 0x47, counter_settings = 0x8A, dark_soul_usage = 0x00, unknown_0e = 0x04, lock_on = 0x00, object_spawn = { variant = 3 } }
artwork = { image = "laserman_image", palette = "laserman_palette_ex" }

[chips."0x0E4".variants]
gregar = { artwork = { icon = 0x08729D50 } }
falzar = { artwork = { icon = 0x0872BE14 } }

[chips."0x0E5"]
name = "LaserMn[SP]"
description = ["A laser", "pierces", "1 thru"]
codes = ["L"]
attack_element = 0
rarity = 4
element = "null"
class = "mega"
mb = 80
power = 200
behavior = { effect_flags = 0x47, counter_settings = 0x8A, dark_soul_usage = 0x00, unknown_0e = 0x04, lock_on = 0x00, object_spawn = { variant = 4 } }
artwork = { image = "laserman_image", palette = "laserman_palette_sp" }

[chips."0x0E5".variants]
gregar = { artwork = { icon = 0x08729D50 } }
falzar = { artwork = { icon = 0x0872BE14 } }
